#!/bin/bash
#
# Copyright 2012    Luis R. Rodriguez <mcgrof@frijolero.org>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# You can keep this in synch with your git tree after running
# This script just update your local copy.

source .compat_copy
UPDATE_SCRIPT="$COMPAT_SRC/scripts/refresh-compat"

if [[ ! -d $COMPAT_SRC ]]; then
	echo -e "You should have compat-wireless.git cloned and checked out under $COMPAT_SRC"
	echo -e "The git tree: git://github.com/mcgrof/compat-wireless.git"
	exit 1
fi

if [[ ! -f $UPDATE_SCRIPT ]]; then
	echo -e "$UPDATE_SCRIPT must exist"
	exit 1
fi

exec $UPDATE_SCRIPT
